stages:
  - ubuntu_build
  - opensuse_build  

opensuse_build:
  image: opensuse/tumbleweed

  before_script:
      - zypper in -y libboost* cppunit-devel python python-devel swig cmake gcc-c++ gcc gnuradio gnuradio-devel

  stage: opensuse_build
  script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        - make
        - cd ..

ubuntu_build:
  image: ubuntu:18.04
  
  variables:
        DEBIAN_FRONTEND: "noninteractive"

  before_script: 
        - apt-get update -qq -y && apt-get install -q -y libboost-all-dev swig cmake g++ gcc gnuradio gnuradio-dev git 
  stage: ubuntu_build
  script:
        - mkdir -p build
        - cd build
        - cmake  ..
        - make

