stages:
  - style 
  - building
  - documentation

style:
  stage: style

  before_script:
    - apt-get update -qq && apt-get install -y -qq astyle git

  script:
    - if (test $(astyle --dry-run --options=.astylerc --formatted lib/*.cc | wc -l) -eq 0); then (exit 0); else (exit 1); fi
    - if (test $(astyle --dry-run --options=.astylerc --formatted lib/*.h | wc -l) -eq 0); then (exit 0); else (exit 1); fi
    - if (test $(astyle --dry-run --options=.astylerc --formatted include/leo/*.h | wc -l) -eq 0); then (exit 0); else (exit 1); fi

opensuse_build:
  image: opensuse/tumbleweed

  before_script:
      - zypper in -y git libboost* cppunit-devel python python-devel swig cmake gcc-c++ gcc orc liborc* gnuradio gnuradio-devel

  stage: building
  script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        - make
        - make install
        - python -c "import leo"

ubuntu_1604_build:
  image: ubuntu:16.04
  
  variables:
        DEBIAN_FRONTEND: "noninteractive"

  before_script: 
        - apt-get update -qq -y && apt-get install -q -y git libboost-all-dev swig cmake g++ gcc gnuradio gnuradio-dev git 
  stage: building
  script:
        - mkdir -p build
        - cd build
        - cmake  ..
        - make
        - make install
        - ldconfig
        - python -c "import leo"

ubuntu_1804_build:
  image: ubuntu:18.04
  
  variables:
        DEBIAN_FRONTEND: "noninteractive"

  before_script: 
        - apt-get update -qq -y && apt-get install -q -y git libboost-all-dev swig cmake g++ gcc gnuradio gnuradio-dev git 
  stage: building
  script:
        - mkdir -p build
        - cd build
        - cmake  ..
        - make
        - make install
        - ldconfig
        - python -c "import leo"

pages:
  image: opensuse/tumbleweed

  before_script:
      - zypper in -y git libboost* cppunit-devel python python-devel swig cmake gcc-c++ gcc doxygen gnuradio gnuradio-devel

  stage: documentation
  script:
      - mkdir -p build
      - cd build
      - rm -rf *
      - cmake  .. 
      - make doxygen_target
      - cd ..
      - rm -rf public/*
      - mv build/docs/doxygen/html public/  
  artifacts:
      paths:
      - public
  only:
  - master
