variables:
  GITLAB_CI_IMAGE_UBUNTU: 'ubuntu:jammy'
  GITLAB_CI_IMAGE_ALPINE: 'alpine:3.15.3'
stages:
  - static
  - build
  - test
  - deploy

# 'static' stage
style:
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  stage: static
  before_script:
    - apt-get -q update
    - apt-get -qy install astyle
  script:
    - 'astyle --dry-run --options=.astylerc --formatted lib/*.cc lib/*.h include/gnuradio/leo/*.h  | sed ''s/^Formatted/ERROR: Unformatted/;T;q1'''

# 'test' stage
ubuntu:
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -q update
    - apt-get -qy install software-properties-common
    - |
      apt-get -qy install \
          libboost-dev \
          libboost-date-time-dev \
          libboost-filesystem-dev \
          libboost-program-options-dev \
          libboost-system-dev \
          libboost-thread-dev \
          libboost-regex-dev \
          libboost-test-dev \
          swig \
          cmake \
          gcc \
          gnuradio-dev \
          libconfig++-dev \
          libgmp-dev \
          liborc-0.4-0 \
          liborc-0.4-dev \
          liborc-0.4-dev-bin \
          libsndfile1-dev \
          git
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make
    - make install
    - ldconfig
    - python3 -c "import gnuradio.leo"

# 'build' stage
docs:
  stage: build
  image: ${GITLAB_CI_IMAGE_UBUNTU}
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -q update
    - apt-get -qy install software-properties-common
    - |
      apt-get -qy install \
          libboost-dev \
          libboost-date-time-dev \
          libboost-filesystem-dev \
          libboost-program-options-dev \
          libboost-system-dev \
          libboost-thread-dev \
          libboost-regex-dev \
          libboost-test-dev \
          swig \
          cmake \
          doxygen \
          gcc \
          gnuradio-dev \
          libconfig++-dev \
          libgmp-dev \
          liborc-0.4-0 \
          liborc-0.4-dev \
          liborc-0.4-dev-bin \
          libsndfile1-dev \
          git
  script:
    - mkdir -p build
    - cd build
    - rm -rf *
    - cmake ..
    - make doxygen_target
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build/docs/doxygen/html

# 'deploy' stage
pages:
  stage: deploy
  image: ${GITLAB_CI_IMAGE_ALPINE}
  script:
    - mv build/docs/doxygen/html/ public/
  artifacts:
    paths:
      - public
  only:
    refs:
      - tags
